input { file { path => "/home/magician/fujikawa/pub/kkcor/*_IND-WKA.csv" start_position => "beginning" sincedb_path => "/tmp/indiv20260721.sincedb" mode => "read" codec => plain { charset => "UTF-8" } } }
filter {
  csv { autodetect_column_names => true }
  mutate { convert => { "dose_final" => "integer" } remove_field => ["message","@version","path","host"] }
}
output { elasticsearch { hosts => ["http://localhost:9200"] index => "indiv20260721" document_id => "%{id}" user => "__ES_ACCOUNT__" password => "__ES_PASSWORD__" manage_template => false } }
