input {
    file {
        path => "/Users/magician/vdeath/afterdose.csv"
        sincedb_path => "/dev/null"
        start_position => "beginning"
    }
}
filter {
    csv {
        autodetect_column_names => true
    }
    date {
        match => [date, "yyyy-MM-dd"]
    }
}
output {
    elasticsearch {
        hosts => ["fujikawa.org:9200"]
        user => "elastic"
        password => "${ES_PASSWORD}"
        index => "afterdose"
        document_id => "%{id}"
        doc_as_upsert => true
        action => "update"
    }
}
